// AUTO-GENERATED by ci/cts/gen_client_tests.py — do not edit manually
//!
//! Thin contract runner for lance-namespace Rust reqwest client.
//!
//! Starts a single WireMock standalone jar with pre-generated mappings (shared
//! across all tests via OnceLock), then exercises every API method to verify HTTP
//! contract compliance and response deserialization.
//!
//! No hand-written fixtures — mappings come from build/cts/wiremock/.
//!
//! Run:   cargo test --test contract -- --nocapture
//! Needs: make gen-cts  (downloads wiremock jar + generates mappings)

use std::net::TcpStream;
use std::path::Path;
use std::process::{Child, Command, Stdio};
use std::sync::OnceLock;
use std::time::{Duration, Instant};

use lance_namespace_reqwest_client::apis::configuration::Configuration;
use lance_namespace_reqwest_client::apis::{data_api, index_api, metadata_api, table_api};
use lance_namespace_reqwest_client::models;

// ---------------------------------------------------------------------------
// WireMock singleton — one process shared across all tests in this binary.
// ---------------------------------------------------------------------------

struct WireMockServer {
    port: u16,
    _child: Child,
}

static WIREMOCK: OnceLock<WireMockServer> = OnceLock::new();

/// Bind port 0 to obtain a free ephemeral port, then release the socket so
/// WireMock can bind it.  There is a brief TOCTOU window; in practice it is
/// negligible for local testing.
fn free_port() -> u16 {
    let listener = std::net::TcpListener::bind("127.0.0.1:0")
        .expect("failed to bind port 0 for free-port allocation");
    listener.local_addr().unwrap().port()
}

/// Obtain (or lazily start) the shared WireMock server.
fn wiremock() -> &'static WireMockServer {
    WIREMOCK.get_or_init(|| {
        let jar = Path::new("../../build/cts/wiremock-standalone.jar");
        let root_dir = Path::new("../../build/cts/wiremock/src/main/resources");

        assert!(
            jar.exists(),
            "WireMock jar not found at {:?}. Run `make gen-cts` first.",
            jar
        );

        let port = free_port();

        let child = Command::new("java")
            .args([
                "-jar",
                jar.to_str().unwrap(),
                "--root-dir",
                root_dir.to_str().unwrap(),
                "--port",
                &port.to_string(),
                "--no-request-journal",
            ])
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .spawn()
            .expect("Failed to spawn WireMock. Is `java` on PATH?");

        wait_for_port(port, Duration::from_secs(30));

        WireMockServer {
            port,
            _child: child,
        }
    })
}

/// Poll until the TCP port accepts connections or the deadline passes.
fn wait_for_port(port: u16, timeout: Duration) {
    let deadline = Instant::now() + timeout;
    loop {
        if TcpStream::connect(format!("127.0.0.1:{port}")).is_ok() {
            return;
        }
        assert!(
            Instant::now() < deadline,
            "WireMock port {port} did not open within {timeout:?}"
        );
        std::thread::sleep(Duration::from_millis(200));
    }
}

/// Build a Configuration pointing at the shared WireMock instance.
fn make_config() -> Configuration {
    let port = wiremock().port;
    Configuration {
        base_path: format!("http://localhost:{port}"),
        ..Default::default()
    }
}

// ---------------------------------------------------------------------------
// Contract tests — one per operation
// ---------------------------------------------------------------------------

#[tokio::test]
async fn contract_alter_table_add_columns() {
    let config = make_config();
    data_api::alter_table_add_columns(
        &config,
        "x",
        models::AlterTableAddColumnsRequest::new(vec![]),
        None,
    )
    .await
    .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_alter_table_alter_columns() {
    let config = make_config();
    metadata_api::alter_table_alter_columns(
        &config,
        "x",
        models::AlterTableAlterColumnsRequest::new(vec![]),
        None,
    )
    .await
    .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_alter_table_backfill_columns() {
    let config = make_config();
    data_api::alter_table_backfill_columns(
        &config,
        "x",
        models::AlterTableBackfillColumnsRequest::new("x".to_string()),
        None,
    )
    .await
    .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_alter_table_drop_columns() {
    let config = make_config();
    metadata_api::alter_table_drop_columns(
        &config,
        "x",
        models::AlterTableDropColumnsRequest::new(vec![]),
        None,
    )
    .await
    .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_alter_transaction() {
    let config = make_config();
    metadata_api::alter_transaction(
        &config,
        "x",
        models::AlterTransactionRequest::new(vec![models::AlterTransactionAction::new()]),
        None,
    )
    .await
    .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_analyze_table_query_plan() {
    let config = make_config();
    data_api::analyze_table_query_plan(
        &config,
        "x",
        models::AnalyzeTableQueryPlanRequest::new(0i32, models::QueryTableRequestVector::new()),
        None,
    )
    .await
    .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_batch_commit_tables() {
    let config = make_config();
    metadata_api::batch_commit_tables(&config, models::BatchCommitTablesRequest::new(vec![]), None)
        .await
        .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_batch_create_table_versions() {
    let config = make_config();
    metadata_api::batch_create_table_versions(
        &config,
        models::BatchCreateTableVersionsRequest::new(vec![]),
        None,
    )
    .await
    .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_batch_delete_table_versions() {
    let config = make_config();
    metadata_api::batch_delete_table_versions(
        &config,
        "x",
        models::BatchDeleteTableVersionsRequest::new(vec![]),
        None,
    )
    .await
    .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_count_table_rows() {
    let config = make_config();
    data_api::count_table_rows(&config, "x", models::CountTableRowsRequest::new(), None)
        .await
        .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_create_namespace() {
    let config = make_config();
    metadata_api::create_namespace(&config, "x", models::CreateNamespaceRequest::new(), None)
        .await
        .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_create_table() {
    let config = make_config();
    data_api::create_table(&config, "x", vec![], None, None, None, None)
        .await
        .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_create_table_index() {
    let config = make_config();
    index_api::create_table_index(
        &config,
        "x",
        models::CreateTableIndexRequest::new("x".to_string(), "x".to_string()),
        None,
    )
    .await
    .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_create_table_scalar_index() {
    let config = make_config();
    index_api::create_table_scalar_index(
        &config,
        "x",
        models::CreateTableIndexRequest::new("x".to_string(), "x".to_string()),
        None,
    )
    .await
    .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_create_table_tag() {
    let config = make_config();
    metadata_api::create_table_tag(
        &config,
        "x",
        models::CreateTableTagRequest::new("x".to_string(), 0i64),
        None,
    )
    .await
    .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_create_table_version() {
    let config = make_config();
    metadata_api::create_table_version(
        &config,
        "x",
        models::CreateTableVersionRequest::new(0i64, "x".to_string()),
        None,
    )
    .await
    .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_declare_table() {
    let config = make_config();
    metadata_api::declare_table(&config, "x", models::DeclareTableRequest::new(), None)
        .await
        .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_delete_from_table() {
    let config = make_config();
    data_api::delete_from_table(
        &config,
        "x",
        models::DeleteFromTableRequest::new("x".to_string()),
        None,
    )
    .await
    .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_delete_table_tag() {
    let config = make_config();
    metadata_api::delete_table_tag(
        &config,
        "x",
        models::DeleteTableTagRequest::new("x".to_string()),
        None,
    )
    .await
    .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_deregister_table() {
    let config = make_config();
    metadata_api::deregister_table(&config, "x", models::DeregisterTableRequest::new(), None)
        .await
        .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_describe_namespace() {
    let config = make_config();
    metadata_api::describe_namespace(&config, "x", models::DescribeNamespaceRequest::new(), None)
        .await
        .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_describe_table() {
    let config = make_config();
    metadata_api::describe_table(
        &config,
        "x",
        models::DescribeTableRequest::new(),
        None,
        None,
        None,
        None,
    )
    .await
    .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_describe_table_index_stats() {
    let config = make_config();
    index_api::describe_table_index_stats(
        &config,
        "x",
        "x",
        models::DescribeTableIndexStatsRequest::new(),
        None,
    )
    .await
    .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_describe_table_version() {
    let config = make_config();
    metadata_api::describe_table_version(
        &config,
        "x",
        models::DescribeTableVersionRequest::new(),
        None,
    )
    .await
    .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_describe_transaction() {
    let config = make_config();
    metadata_api::describe_transaction(
        &config,
        "x",
        models::DescribeTransactionRequest::new(),
        None,
    )
    .await
    .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_drop_namespace() {
    let config = make_config();
    metadata_api::drop_namespace(&config, "x", models::DropNamespaceRequest::new(), None)
        .await
        .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_drop_table() {
    let config = make_config();
    metadata_api::drop_table(&config, "x", None)
        .await
        .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_drop_table_index() {
    let config = make_config();
    index_api::drop_table_index(&config, "x", "x", None)
        .await
        .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_explain_table_query_plan() {
    let config = make_config();
    data_api::explain_table_query_plan(
        &config,
        "x",
        models::ExplainTableQueryPlanRequest::new(models::QueryTableRequest::new(
            0i32,
            models::QueryTableRequestVector::new(),
        )),
        None,
    )
    .await
    .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_get_table_stats() {
    let config = make_config();
    metadata_api::get_table_stats(&config, "x", models::GetTableStatsRequest::new(), None)
        .await
        .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_get_table_tag_version() {
    let config = make_config();
    metadata_api::get_table_tag_version(
        &config,
        "x",
        models::GetTableTagVersionRequest::new("x".to_string()),
        None,
    )
    .await
    .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_insert_into_table() {
    let config = make_config();
    data_api::insert_into_table(&config, "x", vec![], None, None)
        .await
        .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_list_all_tables() {
    let config = make_config();
    table_api::list_all_tables(&config, None, None, None, None)
        .await
        .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_list_namespaces() {
    let config = make_config();
    metadata_api::list_namespaces(&config, "x", None, None, None)
        .await
        .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_list_table_indices() {
    let config = make_config();
    index_api::list_table_indices(&config, "x", models::ListTableIndicesRequest::new(), None)
        .await
        .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_list_table_tags() {
    let config = make_config();
    metadata_api::list_table_tags(&config, "x", None, None, None)
        .await
        .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_list_table_versions() {
    let config = make_config();
    metadata_api::list_table_versions(&config, "x", None, None, None, None)
        .await
        .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_list_tables() {
    let config = make_config();
    metadata_api::list_tables(&config, "x", None, None, None, None)
        .await
        .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_merge_insert_into_table() {
    let config = make_config();
    data_api::merge_insert_into_table(
        &config,
        "x",
        "x",
        vec![],
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    )
    .await
    .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_namespace_exists() {
    let config = make_config();
    metadata_api::namespace_exists(&config, "x", models::NamespaceExistsRequest::new(), None)
        .await
        .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_query_table() {
    let config = make_config();
    let resp = data_api::query_table(
        &config,
        "x",
        models::QueryTableRequest::new(0i32, models::QueryTableRequestVector::new()),
        None,
    )
    .await
    .expect("contract violation: stub returned non-2xx or transport error");
    assert!(
        resp.status().is_success(),
        "contract violation: status = {}",
        resp.status()
    );
}

#[tokio::test]
async fn contract_refresh_materialized_view() {
    let config = make_config();
    data_api::refresh_materialized_view(&config, "x", None, None)
        .await
        .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_register_table() {
    let config = make_config();
    metadata_api::register_table(
        &config,
        "x",
        models::RegisterTableRequest::new("x".to_string()),
        None,
    )
    .await
    .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_rename_table() {
    let config = make_config();
    metadata_api::rename_table(
        &config,
        "x",
        models::RenameTableRequest::new("x".to_string()),
        None,
    )
    .await
    .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_restore_table() {
    let config = make_config();
    metadata_api::restore_table(&config, "x", models::RestoreTableRequest::new(0i64), None)
        .await
        .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_table_exists() {
    let config = make_config();
    metadata_api::table_exists(&config, "x", models::TableExistsRequest::new(), None)
        .await
        .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_update_table() {
    let config = make_config();
    data_api::update_table(&config, "x", models::UpdateTableRequest::new(vec![]), None)
        .await
        .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_update_table_schema_metadata() {
    let config = make_config();
    metadata_api::update_table_schema_metadata(
        &config,
        "x",
        std::collections::HashMap::new(),
        None,
    )
    .await
    .expect("contract violation: stub returned non-2xx or transport error");
}

#[tokio::test]
async fn contract_update_table_tag() {
    let config = make_config();
    metadata_api::update_table_tag(
        &config,
        "x",
        models::UpdateTableTagRequest::new("x".to_string(), 0i64),
        None,
    )
    .await
    .expect("contract violation: stub returned non-2xx or transport error");
}
